#!/bin/bash

#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=10
#SBATCH --mem=240GB
#SBATCH --time=48:00:00
#SBATCH --partition=gpu
#SBATCH --gres=gpu:a40:1
#SBATCH --account=ywang234_1137

module load gcc/11.3.0 python/3.10 cuda/11.6.2 cudnn/8.4.0.27-11.6
pip install torch==2.1+cu111 torchvision==0.16.0+cu111 torchtext==0.16.0 -f https://download.pytorch.org/whl/torch_stable.html
pip install tqdm requests pytorch_lightning==1.9.5 scikit-video av gradio moviepy imageio gdown h5py

python3 main.py