#!/bin/bash

#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=10
#SBATCH --mem=240GB
#SBATCH --time=1:00:00
#SBATCH --partition=gpu
#SBATCH --gres=gpu:a40:1
#SBATCH --account=ywang234_1137

module load gcc/11.3.0 python/3.11.3 cuda/11.8.0 cudnn/8.4.0.27-11.6
pip install torch==2.1+cu118 torchvision==0.16.0+cu118 torchtext==0.16.0 -f https://download.pytorch.org/whl/torch_stable.html
pip install tqdm requests pytorch_lightning==1.9.5 scikit-video av gradio moviepy imageio gdown h5py

python3 test_script.py --trials 5 --batch_size 32 --max_batch 32